manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: efogdev
      url-base: https://github.com/efogdev
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: "v0.3.0"
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: "c9288fb"
    - name: zmk-pointer-2s-mixer
      remote: efogdev
      revision: "eae4984"
    - name: zmk-axis-clamper
      remote: efogdev
      revision: "e3f8b6c"
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: "1400f9f"
    - name: zmk-ec11-ish-driver
      remote: efogdev
      revision: "0a75a5f"
    - name: zmk-auto-hold
      remote: efogdev
      revision: "4682281"
    - name: zmk-trigger-on-boot
      remote: efogdev
      revision: "c06d9d8"
    - name: zmk-behavior-follower
      remote: efogdev
      revision: "76df19c"
    - name: zmk-keymap-shell
      remote: efogdev
      revision: "f65c917"
    - name: zmk-acceleration-curves
      remote: efogdev
      revision: "d8b272a"
  self:
    path: config
